# Spring properties
spring:
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker friendship-server
  thymeleaf:
    cache: false             # Allow Thymeleaf friendship-server to be reloaded at runtime
    prefix: classpath:/posts-server/templates

  rabbitmq:
    host: localhost
    port: 5672
#    virtual-host:
    username: guest
    password: guest

endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true
  refresh:
    enabled: true


# HTTP Server
server:
  port: 0   # HTTP (Tomcat) port

hystrix:
  command:
    RemoteMessageClientCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    RemoteMessageAnnotationClient:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#conf:
#  text: "hello from config!!"
